version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: autoprefixer
    versions:
    - ">= 10.a, < 11"
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - ">= 4.a, < 5"
  - dependency-name: react-spring
    versions:
    - 9.0.0
